language: ruby
sudo: false
env:
- BROWSER=safari EXT=safariextz
script: "./tools/make-${BROWSER}.sh all"
before_install:
- openssl aes-256-cbc -K $encrypted_e984caf80568_key -iv $encrypted_e984caf80568_iv
  -in dist/certs/SafariDeveloper.cer.enc -out dist/certs/SafariDeveloper.cer -d
- openssl aes-256-cbc -K $encrypted_197d257244cd_key -iv $encrypted_197d257244cd_iv
  -in dist/certs/key.pem.enc -out dist/certs/key.pem -d
